name: holoviz
channels:
  - conda-forge
dependencies:
  - geopandas
  - geoviews
  - hvplot
  - jupyterlab=3
  - rioxarray
  - xmlschema
  - xarray=0.18
  - python=3.9
  - pip
  - pip:
    - xarray-sentinel
