# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: uwhackweek/snowex:latest

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Pull Docker Image
      run: |
        docker pull $DOCKER_IMAGE
        docker images

    # NOTE: this gets picked up b/c of the docker run -v mount
    - name: Configure NASA Earthdata Login
      run: |
        echo "machine urs.earthdata.nasa.gov login me password test" > .netrc
        chmod 0600 .netrc
        ls -al .netrc
        id
        
    - name: Parse netrc
      run: |
        docker run --user 1000 \
        -v ${{ github.workspace }}:/home/jovyan:rw \
        $DOCKER_IMAGE python -c "import netrc; (ASF_USER, account, ASF_PASS) = netrc.netrc().authenticators("urs.earthdata.nasa.gov"); print(ASF_USER)"
